version: '3.9'
services:
  minio:
    image: minio/minio:latest
    volumes:
      - minio:/data
    networks:
      - services
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.platform.os==linux"
      rollback_config:
        parallelism: 0
        failure_action: continue
        order: stop-first
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      labels:
        prometheus.job: minio
        prometheus.port: 3700
        prometheus.path: /minio/v2/metrics/cluster
        traefik.enable: 'true'
        traefik.http.routers.minio.rule: Host(`minio.gavanlamb.com`)
        traefik.http.routers.minio.entrypoints: websecure
        traefik.http.routers.minio.tls.certresolver: letsencrypt
        traefik.http.routers.minio.service: minio
        traefik.http.services.minio.loadBalancer.server.port: 3700
        traefik.http.routers.minio-console.rule: Host(`console.minio.gavanlamb.com`)
        traefik.http.routers.minio-console.entrypoints: websecure
        traefik.http.routers.minio-console.tls.certresolver: letsencrypt
        traefik.http.routers.minio-console.service: minio-console
        traefik.http.services.minio-console.loadBalancer.server.port: 3701    
    command: minio server /data --address ":3700" --console-address ":3701"
    environment:
      MINIO_VOLUMES: /data
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_PROMETHEUS_URL: http://prometheus:3600
      MINIO_PROMETHEUS_JOB_ID: minio
    logging:
      options:
        loki-external-labels: "job=minio"

volumes:
  minio:
    name: minio
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.50.32,rw,noatime,rsize=8192,wsize=8192,tcp"
      device: ":/share/docker/minio"

networks:
  services:
    name: services
    external: true
